"""Repository and artifact store protocol interfaces."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from marketing_mcp.repositories.models import ArtifactRef


class MetadataRepository(Protocol):
    """Abstract metadata persistence interface."""

    def put_dataset(self, payload: dict[str, Any]) -> None: ...
    def get_dataset(self, dataset_id: str) -> dict[str, Any]: ...
    def list_datasets(self) -> list[dict[str, Any]]: ...
    def put_model(self, payload: dict[str, Any]) -> None: ...
    def get_model(self, model_id: str) -> dict[str, Any]: ...
    def list_models(self) -> list[dict[str, Any]]: ...
    def put_clv_model(self, payload: dict[str, Any]) -> None: ...
    def get_clv_model(self, model_id: str) -> dict[str, Any]: ...
    def list_clv_models(self) -> list[dict[str, Any]]: ...
    def get_model_unified(self, model_id: str) -> dict[str, Any]: ...
    def put_scenario(self, payload: dict[str, Any]) -> None: ...
    def get_scenario(self, scenario_id: str) -> dict[str, Any]: ...
    def close(self) -> None: ...


class ArtifactStore(Protocol):
    """Abstract artifact storage interface."""

    def model_path(self, model_id: str) -> Path: ...
    def require(self, model_id: str) -> Path: ...
    def put_artifact(self, artifact_id: str, source_path: Path) -> ArtifactRef: ...
